apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: config
webhooks:
- name: webhook.wisecloud-agent.svc
  rules:
  - apiGroups:
    - "*"
    apiVersions:
    - "*"
    operations:
    - CREATE
    resources:
    - deployments
  clientConfig:
    service:
      namespace: wisecloud-agent
      name: webhook
      path: /deployments/mutate
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lKQUlNbmVPU25EUVpVTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ1l4SkRBaUJnTlYKQkFNTUczZGxZbWh2YjJzdWQybHpaV05zYjNWa0xXRm5aVzUwTG5OMll6QWVGdzB4T1RBM01EUXhNREE1TURkYQpGdzB5T1RBM01ERXhNREE1TURkYU1DWXhKREFpQmdOVkJBTU1HM2RsWW1odmIyc3VkMmx6WldOc2IzVmtMV0ZuClpXNTBMbk4yWXpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjJuMzU1cnd5UGsKTEI1Y3RjdnY3STlPYkpmM1ZESS9ncmdJMWdtd2Y5b2NCZzF5Tm1wVGx1cVhuYndUb1ZjTCtWVzgwUFZvMStEUApMSDdBYS8xcE9QR0JkempiZ090ZCtJOFZsVUtkeHVQNkxOaU00YW84VWR4NDB6RjlYbVN2bVltR0x5RGFsQmFDCllFL3JEeVlhcDdTZnZhNTBmVkdRTHJBVnZUNDlUQ0EwWEJLUmcvdGxHeFE3NCszUENiVS9uZUNVMEZXSXZBUTMKRHBZSXRKQUVwaU9xaXpFcHpGeVVEYm94Z0N4cGg1OWVPRVFrYlgyT3l0THk3N0lYRXVpNFc0U2JuR1ZLdjBDTwpTeEtacU1hTXhLRHlXcWt2S21tOUVtYXJrZkIybklwSWNkSUNZUk9LTUM0ekRFb0hTaVJ6UHVlYms2TUI3Tlg1CldrQ3B6K2pzMXNrQ0F3RUFBYU5RTUU0d0hRWURWUjBPQkJZRUZQTlRoeGttWkdQUUxiUU5lYnlEa0d5K0dpWkMKTUI4R0ExVWRJd1FZTUJhQUZQTlRoeGttWkdQUUxiUU5lYnlEa0d5K0dpWkNNQXdHQTFVZEV3UUZNQU1CQWY4dwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRjZGOEtWWVVrL2RLRzVCTS82cE5RMmZ6NXI4NlJ0OU9ONFVtMUh6Ck8xdXRSUWJpLytrWnpCRFBZWTcyMEVpSktuUk5JSll0QTNjZGxqMW8yTFo4ajJsdHVpNWg4L0tCaU1OczdEZWwKYlkwU0JQVVJPOEcxRld0K3A3OTZwUGttck5BT2RwQ2psYVRSV0pxVnViUFF1TnlQbU1tSUFJOEMrOWtlMk1yegpPb2tlQ29LU1ZxajVuOUVLekljM1N6eUZUSUQ1ZmFnSi9wVnJUMGlWcmhmZ0ZzMnFiOUJ5bDErVlFXbjB4N2RWCkZqbTFtS1BCS20zUnM4RnErRUs2TnBOaCtZZkJuR0N0UFpaOUpXSHhMRVM0YnZjN2hFSkp6cWxwaVlraHZrZ2cKWEZYUGZDcWMrSUNaOWpydE5Fdk0zTFNIT2hwQ09GTWJCUlN5aFhwd3RUODlQVTg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K