apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook
rules:
- apiGroups: ["*"]
  resources: ["deployments", "resourcequotas"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook
  namespace: wisecloud-agent
subjects:
- kind: ServiceAccount
  name: webhook
  namespace: wisecloud-agent
roleRef:
  kind: ClusterRole
  name: webhook
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    io.wise2c.stack: wisecloud-agent
  name: webhook
  namespace: wisecloud-agent
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    com.wise2c.service: lb-webhook
    com.wise2c.stack: wisecloud-agent
  name: lb-webhook
  namespace: wisecloud-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      com.wise2c.service: lb-webhook
      com.wise2c.stack: wisecloud-agent
  template:
    metadata:
      labels:
        com.wise2c.service: lb-webhook
        com.wise2c.stack: wisecloud-agent
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/wise2c-test/lb-webhook:master
        imagePullPolicy: IfNotPresent
        name: lb-webhook
        args:
        - "--memory=100m"
        - "--cpu=200m"
        - "--tls-cert-file=/etc/certs/tls.crt"
        - "--tls-private-key-file=/etc/certs/tls.key"
        volumeMounts:
        - mountPath: /etc/certs
          name: config
      serviceAccount: webhook
      volumes:
      - name: config
        secret:
          secretName: lb-webhook-tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    com.wise2c.service: lb-webhook
    com.wise2c.stack: wisecloud-agent
  name: lb-webhook
  namespace: wisecloud-agent
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    com.wise2c.service: lb-webhook
    com.wise2c.stack: wisecloud-agent